# Generated by Django 2.2.1 on 2019-05-20 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dian_code', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Infraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date', models.DateTimeField()),
                ('road_type', models.CharField(choices=[('AV', 'AV'), ('CLL', 'CLL'), ('CR', 'CR')], default='AV', max_length=15)),
                ('road_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('plate', models.CharField(max_length=10)),
                ('infraction_code', models.CharField(max_length=10)),
                ('vehicle_type', models.CharField(max_length=255)),
                ('vehicle_service', models.CharField(max_length=255)),
                ('offender_type', models.CharField(choices=[('driver', 'driver'), ('walker', 'walker'), ('Passenger', 'Passenger')], default='driver', max_length=15)),
                ('offender_document_type', models.CharField(choices=[('CC', 'CC'), ('TI', 'TI'), ('CE', 'CE'), ('PASAPORTE', 'PASAPORTE')], default='CC', max_length=10)),
                ('offender_document_id', models.BigIntegerField()),
                ('offender_name', models.CharField(max_length=255)),
                ('offender_license_id', models.CharField(max_length=100)),
                ('offender_address', models.CharField(max_length=255)),
                ('offender_age', models.IntegerField()),
                ('offender_phone', models.CharField(max_length=50)),
                ('offender_mail', models.CharField(max_length=255)),
                ('owner_document_type', models.CharField(choices=[('CC', 'CC'), ('TI', 'TI'), ('CE', 'CE'), ('PASAPORTE', 'PASAPORTE')], default='CC', max_length=10)),
                ('owner_document_id', models.BigIntegerField()),
                ('owner_name', models.CharField(max_length=255)),
                ('company_id', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=255)),
                ('transit_agent_name', models.CharField(max_length=255)),
                ('transit_agent_entity', models.CharField(max_length=255)),
                ('transit_agent_id', models.BigIntegerField()),
                ('transit_agent_observations', models.CharField(max_length=255)),
                ('document_url', models.CharField(max_length=255)),
                ('state', models.CharField(choices=[('created', 'created'), ('active', 'active'), ('rejected', 'rejected'), ('paid', 'paid')], default='active', max_length=15)),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='multapp.Municipality')),
            ],
        ),
    ]
