# Generated by Django 2.2.1 on 2019-05-21 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multapp', '0002_infraction_state_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infraction',
            name='municipality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='multapp.Municipality'),
        ),
    ]
